//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace test4
{
    using System;
    using System.Collections.Generic;
    
    public partial class ВидыПродуктов
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ВидыПродуктов()
        {
            this.ТоварыНаСкладе = new HashSet<ТоварыНаСкладе>();
        }
    
        public int Код_ВидПродукта { get; set; }
        public string Вид_Продукта { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ТоварыНаСкладе> ТоварыНаСкладе { get; set; }
    }
}
