//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace test4
{
    using System;
    using System.Collections.Generic;
    
    public partial class ДоставкаТовараВМагазин
    {
        public int Код_Доставки { get; set; }
        public Nullable<System.DateTime> Дата_Доставки { get; set; }
        public int Код_Товара { get; set; }
        public Nullable<int> Количество_Товара { get; set; }
        public Nullable<int> Код_Доставщика { get; set; }
        public string Ед_изм { get; set; }
    
        public virtual КомпанииДоставщики КомпанииДоставщики { get; set; }
        public virtual ТоварыНаСкладе ТоварыНаСкладе { get; set; }
    }
}
