//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace test4
{
    using System;
    using System.Collections.Generic;
    
    public partial class ПоставкиНаСклад
    {
        public int Код_Поставки { get; set; }
        public Nullable<System.DateTime> Дата_Поставки { get; set; }
        public int Код_Товара { get; set; }
        public Nullable<int> Код_Поставщика { get; set; }
        public Nullable<int> Количество_Товара { get; set; }
        public string Ед_изм { get; set; }
    
        public virtual КомпанииПоставщики КомпанииПоставщики { get; set; }
        public virtual ТоварыНаСкладе ТоварыНаСкладе { get; set; }
    }
}
